### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by OsmanTunahan** [ruya-tabiri/ruya-tabiri-telegram-botu#1]
Selam **@ruya-tabiri** 👋

Projenizi incelerken dikkat edilmesi gereken önemli bir şey fark ettim. Size bir güvenlik konusu hakkında bilgi vermek istiyorum.
Sanırım **tabir** tablosunda kullandığınız SQL sorgusunda bir güvenlik açığı olabilir. **terim** değişkenini kullanarak yapılan LIKE ifadesi, SQL enjeksiyonu riskine yol açabilir.

Daha güvenli bir yaklaşım için parametreli sorguları düşünebilirsiniz. Örnek vermek gerekirse:
`cekilenveri = imlec.execute("SELECT baslik, icerik FROM tabir WHERE baslik LIKE ? || '%' ", (terim,))`

Bu, kullanıcı girişlerini daha güvenli bir şekilde işler.
Eğer bu konuda yardıma ihtiyacınız olursa veya daha fazla detay istiyorsanız, lütfen benimle iletişime geçmekten çekinmeyin. Güvenlik konularının önemli olduğunu biliyorum ve bu konuda işbirliği yapmaktan memnuniyet duyarım.

İyi kodlamalar,
Osman Tunahan ARIKAN

**Comment by ruya-tabiri** [comment]
Teşekkür ederim gerekli düzeltmeleri ve kontrolleri yapacağım en kısa sürede.
